baseURL = "https://agilitycredit.netlify.com"
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
themesDir = "../.."
title = "Agility Credit"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 Agility Credit LLC. All Rights Reserved."
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.main]]
name = "Home"
url = "#content"
weight = "1"
[[Languages.en.menu.main]]
name = "About"
url = "#about"
weight = "2"

[[Languages.en.menu.footer]]
name = "Privacy"
url = "/privacy"
weight = "2"
[[Languages.en.menu.footer]]
name = "Terms Of Use"
url = "/terms"
weight = "2"
[[Languages.en.menu.footer]]
name = "Do Not Sell My Info"
url = "/do-not-sell"
weight = "2"
[[Languages.en.menu.footer]]
name = "CA Residence Policy"
url = "/ca-residency"
weight = "2"
[[Languages.en.menu.footer]]
name = "Legal Notice"
url = "/legal-notice"
weight = "2"
[[Languages.en.menu.footer]]
name = "Desclaimer"
url = "/desclaimer"
weight = "2"



[[Languages.en.menu.main]]
name = "Solutions"
url = "#solutions"
weight = "3"
[[Languages.en.menu.main]]
name = "Team"
url = "#team"
weight = "4"
[[Languages.en.menu.main]]
name = "Careers"
url = "#careers"
weight = "5"
[[Languages.en.menu.main]]
name = "Contact"
url = "#contact"
weight = "6"
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.main]]
name = "sur"
url = "#about"
weight = 1
[[Languages.fr.menu.main]]
name = "un service"
url = "#services"
weight = 2
[[Languages.fr.menu.main]]
name = "portefeuille"
url = "#portfolio"
weight = 3
[[Languages.fr.menu.main]]
name = "équipe"
url = "#team"
weight = 4
[[Languages.fr.menu.main]]
name = "tarification"
url = "#pricing"
weight = 5
[[Languages.fr.menu.main]]
name = "blog"
url = "#blog"
weight = 6
[[Languages.fr.menu.main]]
name = "contact"
url = "#contact"
weight = 7
[[Languages.fr.menu.main]]
name = "themefisher"
url = "https://themefisher.com/"
weight = 8
[params]
author = "Themefisher"
description = "Responsive Multipurpose Parallax Hugo Template"
google_analytics_id = ""
logo = "images/agility-logo.png"
post_share = true
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = false
preloader = "images/logo.png"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-instagram"
link = "#"
